Some Bug Fixes
qbcore-framework/qb-shops pull request #121
Opened 2022-09-12 10:17 UTC by r0adra93

The previous fix didn't fix the problem. I tested it with a few others on the server and we were able to duplicate the error continuously when users would log on. After several hours of testing, I believe this issue is resolved.

Added PlayerData = QBCore.Functions.GetPlayerData() to several event handlers that were missing it. Without it the shops would not load for players logging into the server.

Fixed a table that was malformed.

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

2022-09-12 13:30 UTC, i-kulgu commented
Tested out and fixed the error : 
![image](https://user-images.githubusercontent.com/29943243/189667110-dadb731b-9fc0-4ca9-9cbf-1973c879e423.png)

2022-09-12 13:49 UTC, i-kulgu commented
Tested out and fixed the error : 
![image](https://user-images.githubusercontent.com/29943243/189667110-dadb731b-9fc0-4ca9-9cbf-1973c879e423.png)

2022-09-12 18:56 UTC, jeann2013 approved these changes

2022-09-13 12:24 UTC, tom-osborne requested changes
@r0adra93 Do you mind checking my comment? Unless I am mistaken, I think the event name was wrong to start with.

2022-09-13 12:24 UTC, tom-osborne commented on client/main.lua
>  end)
I don't think this part is a correct fix. I think the reason this may not have been working is because the event name is wrong. Unless I am mistaken, I doubt that event was ever triggering?

It should be `'QBCore:Player:SetPlayerData'`
https://github.com/qbcore-framework/qb-core/blob/main/server/player.lua#L188

```lua
RegisterNetEvent('QBCore:Player:SetPlayerData', function(val)
    QBCore.PlayerData = val
end)
```

2022-09-13 20:37 UTC, r0adra93 commented on client/main.lua
>  end)
I will test this out
As you know I am new to QBCore and I am learning as I go with it.

2022-09-13 21:47 UTC, r0adra93 commented on client/main.lua
>  end)
@tom-osborne the error is still present when I fix just that one event. This is just one more broken piece of code in the chain of broken code pieces present in this script.
I added the updated event into this PR though.

2022-09-13 22:07 UTC, tom-osborne requested changes

2022-09-13 22:07 UTC, tom-osborne commented on client/main.lua
> +    PlayerData = QBCore.Functions.GetPlayerData()
Sorry bud, but this is still not right. The player data is already passed when this event is triggered, so you don't need to run the `GetPlayerData()` function again. It just needs to be as follows: - 

```lua
RegisterNetEvent('QBCore:Player:SetPlayerData', function(val)
    QBCore.PlayerData = val
end)
```

2022-09-15 02:46 UTC, r0adra93 commented on client/main.lua
> +    PlayerData = QBCore.Functions.GetPlayerData()
Tom,

I fixed the issues as we discussed and tested them profusely with 8 people on the server and leaving and coming back on as if a real game was being played. We were all buying stuff at shops with different jobs, mechanic, police, ambulance, citizen and on and on. No errors were detected concerning this bug issue.

The error with PlayerData.job.name being nil seems to be fixed
The error with PlayerData.metadata['licenses'].weapon being nil seems to be fixed

2022-09-15 07:12 UTC, tom-osborne commented on client/main.lua
> +    PlayerData = QBCore.Functions.GetPlayerData()
Great, good job. Thanks for the effort 👌

2022-09-15 07:13 UTC, tom-osborne approved these changes

2022-09-15 07:13 UTC, merged