Lithuanian
qbcore-framework/qb-shops pull request #124
Opened 2022-09-22 18:58 UTC by Dalgelis

2022-09-23 08:08 UTC, Z3rio commented
You have to follow the Template or include all the information from the template in some way, which this PR saves to do. The default questions are shown upon trying to merge your branch.

2022-09-23 12:04 UTC, Dalgelis commented
Done

2022-09-23 14:20 UTC, Z3rio approved these changes
Looks good to me, not tested ingame though. And I dont know lithuanian so if someone knows the language then please give your feedback on if its good or not :)

2022-11-02 13:30 UTC, tom-osborne requested changes

2022-11-02 13:30 UTC, tom-osborne commented on locale/lt.lua
> +Lang = Locale:new({phrases = Translations})
This needs to handle the `qb_locale` convar for auto-switching locales. Please use the following code:
```lua
if GetConvar('qb_locale', 'en') == 'lt' then
    Lang = Locale:new({
        phrases = Translations,
        warnOnMissing = true,
        fallbackLang = Lang,
    })
end
```

2022-12-13 19:31 UTC, merged