Added jobs and gang grades
qbcore-framework/qb-shops pull request #157
Opened 2023-10-25 07:19 UTC by imgucciwz

Describe Pull request
Added the option to be able to add the items with job and gangs grades.

If your PR is to fix an issue mention that issue here

Questions (please complete the following information):

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) Yes Does your code fit the style guidelines? [yes/no] Yes Does your PR fit the contribution guidelines? [yes/no] Yes

Describe Pull request
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

Questions (please complete the following information):

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
Does your code fit the style guidelines? [yes/no]
Does your PR fit the contribution guidelines? [yes/no]

2023-11-24 10:30 UTC, ChrisNewmanVortex approved these changes
You are awesome, thank you so much <3

2024-01-11 21:26 UTC, citRaTTV requested changes

2024-01-11 21:26 UTC, citRaTTV commented on client/main.lua
> +    for k, v in pairs(list) do
My only concern w/ this change is backwards compat. for folks that are updating an existing deploy. Perhaps we could check to see the type of each key to see if it's an integer or a string, and behave appropriately.

2024-01-15 19:55 UTC, citRaTTV commented on client/main.lua
> +                if curProduct.requiredGang and not tableCheck(PlayerData.gang.name, PlayerData.job.grade.level, curProduct.requiredGang) then
Also, this should be `PlayerData.gang.grade.level`

2024-01-23 15:20 UTC, ChrisNewmanVortex reviewed
Perfecto!

2024-01-23 15:20 UTC, ChrisNewmanVortex commented on client/main.lua
> +    for k, v in pairs(list) do
Worked perfectly for me!

2024-01-23 15:20 UTC, ChrisNewmanVortex approved these changes

2024-01-23 15:21 UTC, ChrisNewmanVortex approved these changes
Works well!

2024-01-29 04:30 UTC, citRaTTV commented on client/main.lua
> +                if curProduct.requiredGang and not tableCheck(PlayerData.gang.name, PlayerData.job.grade.level, curProduct.requiredGang) then
@imgucciwz

2024-04-06 15:44 UTC, closed without merging